# services:
#   frontend:
#     build:
#       context: ./sweet-shop-frontend
#       dockerfile: Dockerfile
#     container_name: node_app
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - backend
#     volumes:
#       - ./sweet-shop-frontend:/usr/src/app
#     command: npm run dev

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: python_app
#     environment:
#        DB_HOST:db
#        DB_PASSWORD:AEXAqYSdqTkOoCvnSKlCNbzAZKNxUvhz
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - db
#     command:
#       sh -c "python manage.py migrate --noinput &&
#              python manage.py runserver 0.0.0.0:8000"

#   db:
#     image: postgres:18
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: sweet_shop
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: AEXAqYSdqTkOoCvnSKlCNbzAZKNxUvhz
#     volumes:
#       - postgres_data:/var/lib/postgresql  

# volumes:
#   postgres_data:


services:
  frontend:
    image: tarungammaedge/sweet_frontend:v2
    build:
      context: ./sweet-shop-frontend
      dockerfile: Dockerfile
      
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./sweet-shop-frontend:/usr/src/app
    command: npm run dev

  backend:
    image: tarungammaedge/sweet_backend:v2
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=railway
      - DB_USER=postgres
      - DB_PASSWORD=AEXAqYSdqTkOoCvnSKlCNbzAZKNxUvhz
      - DB_HOST=caboose.proxy.rlwy.net
      - DB_PORT=12993
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
