services:
  frontend:
    image: tarungammaedge/sweet_frontend:v2
    build:
      context: ./sweet-shop-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: tarungammaedge/sweet_backend:v2
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_NAME: railway
      DB_USER: postgres
      DB_PASSWORD: AEXAqYSdqTkOoCvnSKlCNbzAZKNxUvhz
      DB_HOST: caboose.proxy.rlwy.net
      DB_PORT: 12993
      ALLOWED_HOSTS: "15.206.36.0, 43.205.217.78,localhost,127.0.0.1"
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
