name: CI Pipeline

on :
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout Code
      uses : actions/checkout@v3

    - name : Set up python
      uses : actions/setup-python@v3
      with :
        python-version: '3.10'

    - name : Install Dependencies
      run : |
        pip install -r backend/requirements.txt
    
    - name : Run tests
      run : |
        python backend/manage.py test
